DISEASE_FOLLOW_UPS = {
    "fungal infection": ["Are you experiencing severe itching in the affected area?", "Is the rash spreading to other parts of your body?"],
    "allergy": ["Do you have a personal or family history of allergies?", "Have you been exposed to any known allergens recently?"],
    "gerd": ["Does the chest pain worsen when you lie down or bend over?", "Are you experiencing a sour or bitter taste in your mouth?"],
    "chronic cholestasis": ["Have you noticed any yellowing of your skin or eyes?", "Are you experiencing dark urine or pale stools?"],
    "drug reaction": ["Have you recently started any new medication?", "Do you have any known drug allergies?"],
    "peptic ulcer diseae": ["Does eating relieve or worsen your abdominal pain?", "Have you noticed any black or bloody stools?"],
    "aids": ["Have you had a persistent fever or night sweats?", "Are you experiencing unexplained weight loss?"],
    "diabetes": ["Are you feeling unusually thirsty or urinating more often?", "Do you have any cuts or bruises that are slow to heal?"],
    "gastroenteritis": ["Are you able to keep fluids down?", "Have you had a fever along with the diarrhea?"],
    "bronchial asthma": ["Do you experience wheezing when you breathe?", "Is your coughing worse at night or early morning?"],
    "hypertension": ["Are you experiencing severe headaches or blurred vision?", "Do you have a history of high blood pressure?"],
    "migraine": ["Are you sensitive to light or sound?", "Is the headache throbbing and accompanied by nausea?"],
    "cervical spondylosis": ["Do you feel any numbness or tingling in your arms or hands?", "Is the pain in your neck worsened by movement?"],
    "paralysis (brain hemorrhage)": ["Have you experienced a sudden numbness or weakness on one side of your face or body?", "Are you having trouble speaking or understanding speech?"],
    "jaundice": ["How long have you noticed the yellowing of your skin/eyes?", "Have you had any right-sided abdominal pain?"],
    "malaria": ["Have you traveled recently to a malaria-endemic region?", "Are your chills followed by a high fever and sweating?"],
    "chicken pox": ["Is the rash blistering and itchy?", "Have you had contact with someone who has chickenpox?"],
    "dengue": ["Are you experiencing severe joint and muscle pain?", "Have you noticed any unusual bleeding, like bleeding gums?"],
    "typhoid": ["Are you suffering from a persistent high fever?", "Have you had any stomach pain or constipation/diarrhea?"],
    "hepatitis a": ["Have you eaten any unhygienic or contaminated food recently?", "Are you experiencing severe fatigue and loss of appetite?"],
    "hepatitis b": ["Have you had unprotected intercourse or shared needles recently?", "Are you feeling unusually tired with dark urine?"],
    "hepatitis c": ["Have you received a blood transfusion or had a tattoo recently?", "Are you experiencing joint pain and fatigue?"],
    "hepatitis d": ["Have you previously been diagnosed with Hepatitis B?", "Are you experiencing sudden worsening of jaundice symptoms?"],
    "hepatitis e": ["Have you consumed unpurified water recently?", "Are you pregnant?"],
    "alcoholic hepatitis": ["Have you consumed heavy amounts of alcohol recently?", "Are you experiencing swelling in your abdomen?"],
    "tuberculosis": ["Have you been coughing for more than 3 weeks?", "Are you coughing up any blood or rusty sputum?"],
    "common cold": ["Is your nasal discharge clear or yellowish/greenish?", "Are you experiencing a mild sore throat?"],
    "pneumonia": ["Do you have sharp or stabbing chest pain when you breathe deeply or cough?", "Are you bringing up greenish, yellow, or bloody mucus?"],
    "dimorphic hemmorhoids(piles)": ["Are you experiencing pain or discomfort during bowel movements?", "Have you noticed any bright red blood on the toilet paper?"],
    "heart attack": ["Is the pain radiating to your left arm, jaw, or back?", "Are you feeling short of breath, dizzy, or lightheaded?"],
    "varicose veins": ["Do your legs feel heavy or aching after standing for long periods?", "Are the veins visibly enlarged, bulging, or twisted?"],
    "hypothyroidism": ["Have you been feeling unusually sensitive to the cold?", "Have you noticed unexplained weight gain?"],
    "hyperthyroidism": ["Are you experiencing an unusually rapid or irregular heartbeat?", "Have you noticed unexplained weight loss despite an increased appetite?"],
    "hypoglycemia": ["Are you feeling confused, irritable, or dizzy?", "Have you been sweating excessively?"],
    "osteoarthristis": ["Is your joint pain worse after activity and relieved by rest?", "Do you feel grating or crackling when moving the joint?"],
    "arthritis": ["Are your joints swollen, red, or warm to the touch?", "Is your joint stiffness worse in the morning?"],
    "(vertigo) paroymsal  positional vertigo": ["Does moving your head trigger the dizzy spells?", "Are you experiencing nausea alongside the spinning sensation?"],
    "acne": ["Are you noticing large, painful, pus-filled bumps?", "Is your skin producing excess oil?"],
    "urinary tract infection": ["Are you feeling a frequent or urgent need to urinate?", "Do you experience a burning sensation during urination?"],
    "psoriasis": ["Do you have red patches of skin covered with thick, silvery scales?", "Are your joints swollen and stiff?"],
    "impetigo": ["Is the rash mostly around the nose and mouth?", "Are there honey-colored crusts forming on the sores?"]
}

def get_follow_up_questions(disease: str):
    normalized = disease.lower().strip()
    return DISEASE_FOLLOW_UPS.get(normalized, ["Are there any other symptoms you've noticed?"])
